query getIssues(
  $repoOwner: String!
  $repoName: String!
  $fetchIssuePerPage: Int = 5
  $endCursor: String
) {
  repository(owner: $repoOwner, name: $repoName) {
    issues(
      orderBy: { field: CREATED_AT, direction: DESC }
      first: $fetchIssuePerPage
      after: $endCursor
    ) {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        id
        number
        title
        body
        url
      }
    }
  }
}
